### PR TITLE
#49: Semantics of getLinks

### PR DESCRIPTION
**Pull request by pictavien**
Hi,
I had added to Topology several accessors with the type of links made explicit in the name of the methods:
* getUndirectedLinks, getDirectedLinks  for all links accessors
* getUndirectedLink, getUndirectedLink for the single link accessor.
I also add a new accessor Node.getCommonUndirectedLinkWith.
Replaced methods have been marked as deprecated.

### CODE REVIEW

**Comment by remikey** [comment]
@pictavien , please rebase over `develop` after latest merges.

**Comment by acasteigts** [comment]
Thank you @pictavien. Here are a few suggestions after discussion with @remikey. Could you please:

- Rename the enum type `Link.Type` into `Link.Orientation`, this breaks the API but is OK.
  (this is a much better name and currently `Mode` versus `Type` are confusing)
- Replace the boolean `isDirectedGraph` by a field `orientation` of the above type
- Replace `setDirectedGraph()` by `setOrientation()` using `Link.Orientation` as parameter
- Add corresponding getter (`getOrientation()`)
- Deprecate method `hasDirectedLinks`, while having it behave as previously 
  (only checking the size of arcs versus edges)
- Instead, add a `isDirected()` method (without "Graph") that uses only the `orientation` field that returns a boolean
- Replace `getDirectedLinks()` and `getUndirectedLinks()` by the following versions of `getLinks`:
  + with parameter of type `Link.Orientation`, returns directed or undirected links irrespective of the current `orientation` field
  + without parameter, calls the first using the current value of the field `orientation`
- Still deprecate the old `getLinks(boolean)`

In addition, you could please: 

- Add a few unit tests for basic use cases (adding directed edges, getting undirected edges etc.)
- Replace the \<tt\> markups by \<code\> ones
- Remember to adapt the changelog accordingly

**Comment by pictavien** [comment]
Job is done. Hope all is covered.

**Comment by remikey** [comment]
Thank you @pictavien , after discussion with @acasteigts , would you please consider the following remarks?

### `Topology.java`

* As for `getLinks(*)`, 
  * create `getLink(Node, Node, Link.Orientation)`
  * deprecate `getLink(Node from, Node to, boolean directed)` and use the new version
  * please remove `getDirectedLink()` and `getUndirectedLink()`, since the new `getLink()` variation is clear enough
* In `Topology.hasDirectedLinks()`'s implementation, unnecessary parenthesis remain
* line 718, javadoc issue: `"()"`

### `OrientationTest.java`

Good job with testing a lot of possibilities where nothing was tested before!
 
* as discussed, could you please clarify/split the threefold assertions?

### `CHANGELOG.md`

* The documentation for `Topology.hasDirectedLinks()` does not match the implementation (the implementation is correct). Only keep the deprecate part.
* add `getLink(*)` part
* remove `getDirectedLink()` and `getUndirectedLink()` part
* "wrt"/"w.r.t."?
* explicitely state that `Link.DEFAULT_TYPE` has been renamed into `Link.DEFAULT_ORIENTATION`
* `"...is changed to explicit invoke undirected..."` -> `"...is changed to explicitly invoke undirected..."`


### Note for later

Since the review starts to be long, at the end of this PR, we should squash a lot (if not everything) on git.

**Comment by pictavien** [comment]
Changes are pushed.

**Comment by remikey** [comment]
ok for me.

**Pull request merged**
