### PR TITLE
#55: New dot parser without digraph-parser

### PR DESCRIPTION
**Pull request by pictavien**
The new parser is always based on ANTLR but we get rid of digraph-parser dependency. 
Due to ANTLR runtime we always inherit the dependency to TreeLayout.

### CODE REVIEW

**Comment by remikey** [comment]
@pictavien , please rebase over `develop` after latest merges.

**Comment by remikey** [comment]
Thank you for the contribution! My remarks:

* `build.gradle`:
  * actually remove `com.paypal.digraph.digraph-parser` dependency
  * since we have changed from antlr `4.2` to `4.5`, why not `4.7.+` ?

* Please explicitly note provenance/licence of files coming from other projects (directly in the source if relevant, in the pull request if not):
  * sources
  * test files


* `CHANGELOG.md`:
  * Incorrect name of dependency in title : 
    * Should be `com.paypal.digraph.digraph-parser`
  * Explicitly write that we have removed the dependency to  `com.paypal.digraph.digraph-parser`
  * `"* ANTLR runtime classes are always ..."` -> `"* ANTLR runtime classes are still ..."`
  * I am not sure that the fact that we use the gradle plugin is relevant for the user. 
  * State that now the parser actually tells the difference between undirected and directed graphs

* `lib/jbotsim-serialization-common/README.md`:
  * ANTLR version does not match the one used by the build (change after updating the build value, if relevant)
  * "dependency"/"dependencies" modifications seem odd to me (at least 2 places)

* `lib/README.md` must be updated with new dependency tree:
  * search for paypal
  * please do not modify JBotSim's current version number (it will be done in batch during release)
  * `./gradlew lib:jbotsim-serialization-common:dependencies`
  * `./gradlew lib:jbotsim-ui-swing:dependencies`
  * `./gradlew lib:jbotsim-extras-swing:dependencies`
  * `./gradlew lib:jbotsim-all:dependencies`
  * `./gradlew lib:jbotsim-common:dependencies`

 * `DotTopologySerializer.java`:
   * `GotGraph G`  does not match java variables naming conventions

* Please add copyright notice in new java files
* If relevant, provide a succinct class description for new java classes

 * Unit tests:
   * why have previous files been modified? ( `sunlet-10-directed.gv-res.xml` ) I understand it is because we now handle digraphs properly?
   * Is it mandatory to use test files from paypal's digraph-parser project ?
   * If possible, please anotate new resource files so that we know where they come from (generated with a tool, generated by hand, coming from another project)

* make sure one last time that we don't refer to digraph-parser anywhere in the project

**Comment by pictavien** [comment]
Le 06/08/2019 à 14:43, Rémi a écrit :
>
> Thank you for the contribution! My remarks:
>
>  *
>
>     |build.gradle|:
>
>       o actually remove |com.paypal.digraph.digraph-parser| dependency
>       o since we have changed from antlr |4.2| to |4.5|, why not |4.7.+| ?
>
I have upgraded the version to 4.7.+. It adds new dependencies:
     |    |    |    +--- org.antlr:antlr4:4.7.+ -> 4.7.2
     |    |    |    |    +--- org.antlr:antlr4-runtime:4.7.2
     |    |    |    |    +--- org.antlr:antlr-runtime:3.5.2
     |    |    |    |    +--- org.antlr:ST4:4.1
     |    |    |    |    |    \--- org.antlr:antlr-runtime:3.5.2
     |    |    |    |    +--- 
org.abego.treelayout:org.abego.treelayout.core:1.0.3
     |    |    |    |    +--- org.glassfish:javax.json:1.0.4
     |    |    |    |    \--- com.ibm.icu:icu4j:61.1
>
>  *
>
>     Please explicitly note provenance/licence of files coming from
>     other projects (directly in the source if relevant, in the pull
>     request if not):
>
>       o sources
>       o test files
>
Done. It could be a good idea to add in Serializers some code to produce 
comments indicating the origin of generated files.

>  *
>
>     If relevant, provide a succinct class description for new java classes
>
>  *
>
>     Unit tests:
>
>       o why have previous files been modified? (
>         |sunlet-10-directed.gv-res.xml| ) I understand it is because
>         we now handle digraphs properly?
>
Exactly.

**Comment by remikey** [comment]
Next iteration. Hopefully the last!

* `CHANGELOG.md`:
  * "[issue 55]" is unclickable
  
    There is something wrong with the space character in the link definition (when I copy paste the definition of 49 and replace "49"s by "55"s, it works properly. Please fix it.

* The generated artefact should not depend on the whole `antlr` distribution; `antlr-runtime` should be enough.
  
  I'll send you a patch containing a workaroud for the related issue (coming from antlr plugin):
  * I have chosen to hardcode the 4.7.2 dependency (so that we know what we ship). Feel free to modify it as you think is the best.
  * The former dependency to `treelayout` is not present anymore with this version. You will need to `lib/jbotsim-serialization-common/README.md` accordingly

* `lib/README.md` :
  * Please update dependency trees with solely `antlr4-runtime`

* `lib/jbotsim-serialization-common/README.md`:
  * Please update with the single remaining dependency (singular :-) ) 

* I think the following files could contain a generation-related annotation (they contain a copyright) ? Only apply what you think fits.
  * `dotinputs/`
	  * syntax-01.xdot
	  * syntax-02.xdot
	  * syntax-03.xdot
	  * syntax-04.xdot
  * `xmlinputs/`
	  * bad-dst-node.xml
	  * empty-graph.xml
	  * imcomplete-model-class-1.xml
	  * imcomplete-model-class-2.xml
	  * imcomplete-model-class-3.xml
	  * imcomplete-clock-class.xml
	  * imcomplete-link-resolver-class.xml
	  * imcomplete-message-engine-class.xml
	  * imcomplete-node-class.xml
	  * imcomplete-scheduler-class.xml
	  * missing-classes.xml
	  * missing-dst.xml
	  * missing-graph.xml
	  * missing-src.xml
	  * named-node-models.xml
	  * no-default-constructor.xml
	  * node-redeclared.xml
	  * twonodes.xml
	  * unknown-model-class.xml
	 


I think that adding a generation comment when generating serializing a Topology could indeed be a good feature! Feel free to create a ticket so that it be discussed.

**Comment by pictavien** [comment]
I've made changes. 
For xmlinputs/* files they were written by hand.

**Comment by remikey** [comment]
Thank you for the clean squash (you could have squashed my small contribution too). Good for me.

**Pull request merged**
